services:
  nexo-bot:
    image: ksmaiotupnvj/nexo-bot:latest
    container_name: nexo_bot
    restart: always
    ports:
      - "8002:8000"
    environment:
      - DISCORD_BOT_TOKEN
      - PORT
      - HOST
      - DATABASE_URL
      - GITHUB_SECRET
      - ANNOUNCEMENT_CHANNEL_ID
      - WEBHOOK_DEVLOGS_CHANNEL_ID
      - WEBHOOK_RELEASE_NOTES_CHANNEL_ID
      - WELCOME_AND_RULES_CHANNEL_ID
      - LLAMA_SERVER_URL
      - LLAMA_TOKENIZE_URL
      - MCP_SERVER_URL
      - GOOGLE_SERVICE_ACCOUNT_FILE
      - GOOGLE_CALENDAR_ID
      - LLAMA_API_KEY
      - GENERATOR_CHANNEL_ID
      - CATEGORY_ID
      - MEMBER_ROLE_ID
    volumes:
      - ./prompts:/app/prompts
      - ./data:/app/data
      - /home/admin-iot-hydroponik/ksm-aiot/nexo/credentials:/app/credentials:ro
      - /home/admin-iot-hydroponik/ksm-aiot:/home/admin-iot-hydroponik/ksm-aiot:ro
    dns:
      - 8.8.8.8
      - 1.1.1.1
    deploy:
      resources:
        limits:
          memory: 300M
    networks:
      - hydroponic_network

networks:
  hydroponic_network:
    external: true
